SELECT DISTINCT
	DP.CODIGO_PESQUISA AS 'ID PESQUISA',
	DP.DATA_PROCESSAMENTO AS 'DATA_PROCESSAMENTO_DW',
	DC.CODIGO_VENDA AS 'ID VENDA',
	CASE 
		WHEN DP.DATA_CADASTRO IS NULL AND DP.CODIGO_PESQUISA LIKE '%O%' THEN CONVERT(CHAR, DP.DATA_RESPOSTA, 23)
		WHEN DP.DATA_CADASTRO IS NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23)
		ELSE CONVERT(CHAR, DP.DATA_CADASTRO, 23)
	END AS 'DATA 1º ENVIO',
	CASE 
		WHEN DP.DATA_DISPARO IS NULL THEN CONVERT(CHAR, DP.DATA_CADASTRO, 23)
		WHEN (CASE WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN DP.DATA_DISPARO ELSE DP.DATA_RESPOSTA END
		< CASE WHEN DP.DATA_DISPARO IS NULL THEN DP.DATA_CADASTRO ELSE DP.DATA_DISPARO END) THEN CONVERT(CHAR, DP.DATA_CADASTRO, 23)
		ELSE CONVERT(CHAR, DP.DATA_DISPARO, 23)
	END AS 'DATA_ULTIMO_ENVIO',
	CASE
		WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23)
		WHEN DP.CODIGO_PESQUISA IN ('102975','103113','104382','106282','108704','108767','109716','111373','111710','114780','115199','115199','115768','118068') THEN '2022-01-18'
		ELSE CONVERT(CHAR, DP.DATA_RESPOSTA, 23)
	END AS 'DATA RESPOSTA',
	CONVERT(CHAR, (CASE	WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN DP.DATA_DISPARO ELSE DP.DATA_RESPOSTA END), 108) AS 'HORA RESPOSTA',
	CASE
		WHEN DP.DATA_RESPOSTA IS NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23)
		WHEN DP.CODIGO_PESQUISA IN ('102975','103113','104382','106282','108704','108767','109716','111373','111710','114780','115199','115199','115768','118068') THEN '2022-01-18'
		ELSE CONVERT(CHAR, DP.DATA_RESPOSTA, 23)
	END AS 'DATA REFERENCIA TR',
	CASE
		WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NULL AND DATEADD(DAY,5,DP.DATA_DISPARO) >= SYSDATETIME() THEN 'NÃO'
		WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NULL AND DATEADD(DAY,5,DP.DATA_DISPARO) < SYSDATETIME() THEN 'SIM'
		WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NULL AND DP.DATA_DISPARO IS NULL THEN 'NÃO'
		ELSE 'RESPONDIDA'
	END AS 'PESQUISA EXPIRADA?',
	CASE
		WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
		WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
		ELSE DE.TIPO_EMPRESA 
	END AS 'EMPRESA',
	CASE 
		WHEN CASE WHEN SR.NOME_REGIONAL IS NULL THEN SR2.NOME_REGIONAL ELSE SR.NOME_REGIONAL END = 'RIBEIRÃO PRETO' THEN 'RIBEIRAO PRETO'
		WHEN SCD1.NOME_CIDADE = 'UBERABA' THEN 'UBERABA'
		WHEN SR.NOME_REGIONAL = 'MATÃO' THEN 'ARARAQUARA'
		WHEN SR.NOME_REGIONAL = 'CRAVINHOS' THEN 'RIBEIRAO PRETO'
		WHEN SR.NOME_REGIONAL IS NULL AND SCD1.NOME_CIDADE IN ('SERTAOZINHO','JABOTICABAL') THEN 'RIBEIRAO PRETO'
		WHEN SR.NOME_REGIONAL IS NULL AND SCD1.NOME_CIDADE = 'FRANCA' THEN 'FRANCA'
		ELSE SR.NOME_REGIONAL
	END AS 'MACRORREGIONAL',
	CASE
		WHEN SCD1.NOME_CIDADE IS NULL THEN 'RIBEIRAO PRETO'
		WHEN SCD1.NOME_CIDADE = 'SÃO J. DO RIO P' THEN 'SÃO JOSÉ DO RIO PRETO'
		WHEN SCD1.NOME_CIDADE = 'SÃO JOSÉ DO RIO' THEN 'SÃO JOSÉ DO RIO PRETO'
		WHEN SCD1.NOME_CIDADE IN ('CRAVINHOS', 'JABOTICABAL', 'SERRANA', 'SERTAOZINHO') THEN 'RMRP'
		WHEN SCD1.NOME_CIDADE IN ('MATAO', 'MATÃO', 'TAQUARITINGA') THEN 'RMARA'
		WHEN SCD1.NOME_CIDADE = 'BOTUCATU' THEN 'RMBRU'
		WHEN SCD1.NOME_CIDADE = 'PAULINIA' THEN 'RMCAM'
		WHEN SCD1.NOME_CIDADE = 'LIMERIA' THEN 'RMPIR'
		WHEN SCD1.NOME_CIDADE = 'VOTORANTIM' THEN 'SOROCABA'
		ELSE SCD1.NOME_CIDADE 
	END AS 'MICRORREGIONAL',
	CASE UPPER(DCP.NOME_CAMPANHA)
		WHEN 'BILD BOAS VINDAS' THEN 'BOAS VINDAS'
		WHEN 'BILD CRM_ASSISTÊNCIA TÉCNICA' THEN 'ASSISTÊNCIA TÉCNICA'
		WHEN 'BILD CRM_DISTRATO' THEN  'DISTRATO'
		WHEN 'BILD CRM_RENEGOCIAÇÃO' THEN 'RENEGOCIAÇÃO'
		WHEN 'BILD VISTORIA ENTREGA CHAVE' THEN 'VISTORIA ENTREGA DE CHAVES'
		WHEN 'BILD VISTORIA ESTOQUE' THEN 'VISTORIA ENTREGA DE CHAVES'
		WHEN 'BILD_12 MESES DA ENTREGA DE CHAVES' THEN '12 MESES PÓS ENTREGA DE CHAVES'
		WHEN 'BILD_6 MESES DA ENTREGA DE CHAVES' THEN '6 MESES PÓS ENTREGA DE CHAVES'
		WHEN 'BILD_BILD DESIGN' THEN 'PERSONALIZAÇÃO'
		WHEN 'BILD_ENTREGA DE CHAVES' THEN 'ENTREGA DE CHAVES'
		WHEN 'BILD_REPASSE' THEN 'REPASSE'
		WHEN 'VITTA 12 MESES DA ENTREGA DE CHAVES' THEN '12 MESES PÓS ENTREGA DE CHAVES'
		WHEN 'VITTA 30 DIAS DA ENTREGA DE CHAVES' THEN '30 DIAS PÓS ENTREGA DE CHAVES'
		WHEN 'VITTA 6 MESES DA ENTREGA DE CHAVES' THEN '6 MESES PÓS ENTREGA DE CHAVES'
		WHEN 'VITTA BOAS VINDAS' THEN 'BOAS VINDAS'
		WHEN 'VITTA CRM DISTRATO' THEN 'DISTRATO'
		WHEN 'VITTA CRM RENEGOCIAÇÃO' THEN 'RENEGOCIAÇÃO'
		WHEN 'VITTA CRM_ASSISTÊNCIA TÉCNICA' THEN 'ASSISTÊNCIA TÉCNICA'
		WHEN 'VITTA ENTREGA DE CHAVES' THEN 'ENTREGA DE CHAVES'
		WHEN 'VITTA REPASSE (CRÉDITO IMOBILIÁRIO)' THEN 'REPASSE'
		WHEN 'VITTA VISTORIA DE ENTREGA DE CHAVES' THEN 'VISTORIA ENTREGA DE CHAVES'
		WHEN 'VITTA VISTORIA ESTOQUE' THEN 'VISTORIA ENTREGA DE CHAVES'
		WHEN 'VITTA VITTA MAIS' THEN 'PERSONALIZAÇÃO'
		ELSE NULL
	END AS 'CAMPANHA',
	SC.NOME_CLIENTE AS 'NOME CLIENTE', -- EXCLUSIVO
	CASE
		WHEN SE.NOME_EMPREENDIMENTO IS NULL THEN SE2.NOME_FANTASIA_EMPREENDIMENTO
		ELSE SE.NOME_EMPREENDIMENTO
	END AS 'NOME EMPREENDIMENTO',
	SE.DATA_LANCAMENTO_EMPREENDIMENTO AS 'DATA LANÇAMENTO',
	SE.DATA_PRAZO_ENTREGA_EMPREENDIMENTO AS 'DATA PREVISÃO ENTREGA',
	SE.DATA_CHAVES_EMPREENDIMENTO AS 'DATA PREVISÃO ENTREGA DE CHAVES',
	SE.DATA_ENTREGA_REAL_EMPREENDIMENTO AS 'DATA REAL ENTREGA DE CHAVES',
	SU.CODIGO_MEGA AS 'CODIGO UNIDADE', -- CORREÇÃO ID VENDA
	CASE
		WHEN SU.NOME_TORRE = (CASE WHEN SE.NOME_EMPREENDIMENTO IS NULL THEN SE2.NOME_FANTASIA_EMPREENDIMENTO ELSE SE.NOME_EMPREENDIMENTO END) THEN 'TORRE ÚNICA'
		ELSE SU.NOME_TORRE
	END	AS 'TORRE',
	CASE
		WHEN SU.NOME_BLOCO IS NULL THEN 'BLOCO ÚNICO'
		ELSE SU.NOME_BLOCO 
	END AS 'BLOCO',
	SU.NOME_APARTAMENTO AS 'UNIDADE',
	CASE
		WHEN SCD1.NOME_CIDADE IS NULL THEN 'RIBEIRAO PRETO'
		WHEN SCD1.NOME_CIDADE = 'SÃO J. DO RIO P' THEN 'SAO JOSE DO RIO PRETO'
		WHEN SCD1.NOME_CIDADE = 'SÃO JOSÉ DO RIO' THEN 'SAO JOSE DO RIO PRETO'
		ELSE SCD1.NOME_CIDADE 
	END AS 'CIDADE EMPREENDIMENTO', -- NOVO APONTAMENTO PARA CIDADE DA OBRA
	DE.FASE_EMPREENDIMENTO AS 'FASE EMPREENDIMENTO',
	CASE STP.NOME_TIPO_PRODUTO
		WHEN '200A500' THEN '200K - 500K'
		WHEN '501A1MILHA' THEN '501K - 1M'
		WHEN 'ACIMA1MILHA' THEN 'ACIMA DE 1M'
		WHEN 'TERREO' THEN 'TERREO +3'
		ELSE STP.NOME_TIPO_PRODUTO
	END AS 'SORTIMENTO',
	CASE
		WHEN DP.ORIGEM_DISPARO = 'EMAIL' THEN 'E-MAIL'
		WHEN DP.ORIGEM_DISPARO = 'Ligação' THEN 'SMS'
		WHEN DP.ORIGEM_DISPARO = '' THEN 'SMS'
		ELSE DP.ORIGEM_DISPARO
	 END AS 'FONTE ÚLTIMO ENVIO',
	 	CASE
		WHEN DP.ORIGEM_DISPARO = 'EMAIL' THEN 'E-MAIL'
		WHEN DP.ORIGEM_DISPARO = 'Ligação' THEN 'LIGAÇÃO'
		WHEN DP.ORIGEM_DISPARO = '' THEN 'SMS'
		ELSE DP.ORIGEM_DISPARO
	 END AS 'FONTE RESPOSTA',
	 CASE
		WHEN (DP.TIPO_RESPOSTA IS NULL) AND (DP.NOTA_RESPOSTA IS NOT NULL) THEN 'CLIENTE'
		WHEN (DP.TIPO_RESPOSTA = '') AND (DP.NOTA_RESPOSTA IS NOT NULL) THEN 'CLIENTE'
		WHEN DP.ORIGEM_DISPARO = 'Ligação' THEN 'LIGAÇÃO'
		WHEN DP.TIPO_RESPOSTA = '' THEN NULL
		ELSE UPPER(DP.TIPO_RESPOSTA)
	END AS 'TIPO RESPOSTA',
	SH.NOME_HOUSE AS 'HOUSE',
	SG.NOME_GH AS 'GH',
	SGV.NOME_GV AS 'GV',
	SCS.NOME_CONSULTOR AS 'CORRETOR',
	CASE
		WHEN SH.NOME_HOUSE LIKE '%VENDA INTERNA%' OR SG.NOME_GH LIKE '%VENDA INTERNA%' OR SGV.NOME_GV LIKE '%VENDA INTERNA%' OR SCS.NOME_CONSULTOR LIKE '%VENDA INTERNA%'
			OR SH.NOME_HOUSE LIKE '%VENDAS INTERNAS%' OR SG.NOME_GH LIKE '%VENDAS INTERNAS%' OR SGV.NOME_GV LIKE '%VENDAS INTERNAS%' OR SCS.NOME_CONSULTOR LIKE '%VENDAS INTERNAS%'
				THEN 'VENDA INTERNA'
		WHEN SCS.EMAIL_CONSULTOR LIKE '%BILD%' OR SCS.EMAIL_CONSULTOR LIKE '%VITTA%' THEN 'HOUSE PRÓPRIA'
		ELSE 'IMOBILIÁRIA'
	END AS 'TIPO VENDA',
	DE.GESTOR_ENGENHARIA AS 'GESTOR ENGENHARIA',
	UPPER(DE.ENGENHEIRO_RESPONSAVEL) AS 'ENGENHEIRO RESPONSÁVEL',
	DE.TECNICO_RESPONSAVEL AS 'TÉCNICO RESPONSÁVEL',
	DP.NOTA_RESPOSTA AS 'NOTA',
	CASE
		WHEN DP.NOTA_RESPOSTA <= 6 THEN 'DETRATOR'
		WHEN DP.NOTA_RESPOSTA BETWEEN 7 AND 8 THEN 'NEUTRO'
		WHEN DP.NOTA_RESPOSTA >= 9 THEN 'PROMOTOR'
		ELSE NULL
	END AS 'CLASSIFICAÇÃO NPS',
	CASE 
		WHEN DP.NOTA_RESPOSTA IS NULL THEN 'NÃO'
		WHEN DP.NOTA_RESPOSTA IS NOT NULL THEN 'SIM'
		ELSE NULL
	END AS 'PESQUISA RESPONDIDA?',
	DP.COMENTARIO_RESPOSTA AS 'COMENTÁRIO DO CLIENTE',
	DP.COMENTARIO_EMPRESA AS 'COMENTÁRIO DA EMPRESA',
	CASE
		WHEN DP.NOTA_RESPOSTA <= 6 THEN -100
		WHEN DP.NOTA_RESPOSTA BETWEEN 7 AND 8 THEN 0
		WHEN DP.NOTA_RESPOSTA >= 9 THEN 100
		ELSE NULL
	END AS 'NPS',
	DPIX.PESO AS 'PESO ISC MACROREGIONAL',
	DPI.PESO AS 'PESO ISC REGIONAL',
	DPI.PESO_GERAL AS 'PESO ISC GERAL',
	DPI.META AS 'META ISC REGIONAL',
	DPI.META_GERAL AS 'META ISC EMPRESA',
	DPI.META_NPS AS 'META NPS REGIONAL',
	DPI.META_NPS_GERAL AS 'META NPS EMPRESA',
	DPIC.PESO AS 'PESO ISC CIDADE',
	DPIC.META AS 'META ISC CIDADE',
	DPIC.META_NPS AS 'META NPS CIDADE',
	CASE 
		WHEN DP.NOTA_RESPOSTA IS NULL THEN 0
		WHEN DP.NOTA_RESPOSTA IS NOT NULL THEN 100
		ELSE NULL
	END AS 'TAXA RESPOSTA',
	VV.VISAO AS 'VISÃO 30%',
	VV.V_DATA_ENTREGA_CHAVES AS 'DATA ENTREGA DE CHAVES'
	FROM
		DMDexc.D_PESQUISA DP
			LEFT JOIN DMDexc.D_CAMPOS DC ON DP.SK_D_CAMPOS = DC.SK_CAMPOS
				LEFT JOIN DMDexc.D_EMPREENDIMENTO DE ON DC.SK_D_EMPREENDIMENTO = DE.SK_EMPREENDIMENTO
					LEFT JOIN DMSys.D_REGIONAL SR ON DE.CODIGO_REGIONAL = SR.CODIGO_REGIONAL
			LEFT JOIN DMDexc.D_CAMPANHA DCP ON DP.SK_D_CAMPANHA = DCP.SK_CAMPANHA
				LEFT JOIN DMSys.F_VENDA SV ON DC.CODIGO_VENDA = SV.CODIGO_VENDA
					LEFT JOIN DMSys.D_CLIENTE SC ON SV.SK_D_CLIENTE_01 = SC.SK_CLIENTE
					LEFT JOIN DMSys.D_EMPREENDIMENTO SE ON DE.CODIGO_SYS_EMPREENDIMENTO = SE.CODIGO_EMPREENDIMENTO
					LEFT JOIN DMSys.D_UNIDADE SU ON SV.SK_D_UNIDADE = SU.SK_UNIDADE
						LEFT JOIN DMSys.D_CIDADE SCD ON SE.SK_D_CIDADE_EMPREENDIMENTO = SCD.SK_CIDADE
							LEFT JOIN DMSys.D_CIDADE SCD1 ON SE.SK_D_CIDADE_OBRA = SCD1.SK_CIDADE -- CIDADE DA OBRA
					LEFT JOIN DMSys.F_EMPREENDIMENTO SEP ON SV.SK_D_EMPREENDIMENTO = SEP.SK_D_EMPREENDIMENTO
						LEFT JOIN DMSys.D_TIPO_PRODUTO STP ON SEP.SK_D_TIPO_PRODUTO = STP.SK_TIPO_PRODUTO
					LEFT JOIN DMSys.D_HOUSE SH ON SV.SK_D_HOUSE = SH.SK_HOUSE
					LEFT JOIN DMSys.D_GH SG ON SV.SK_D_GH = SG.SK_GH
					LEFT JOIN DMSys.D_GV SGV ON SV.SK_D_GV = SGV.SK_GV
					LEFT JOIN DMSys.D_CONSULTOR SCS ON SV.SK_D_CONSULTOR = SCS.SK_CONSULTOR
					LEFT JOIN DMSys.D_TIPO_EMPREENDIMENTO STE ON SV.SK_D_TIPO_EMPREENDIMENTO = STE.SK_TIPO_EMPREENDIMENTO
					LEFT JOIN DMSys.D_REGIONAL SR2 ON SV.SK_D_REGIONAL = SR2.SK_REGIONAL
					LEFT JOIN DMSys.D_EMPREENDIMENTO SE2 ON SV.SK_D_EMPREENDIMENTO = SE2.SK_EMPREENDIMENTO
			LEFT JOIN DMDexc.D_PESO_ISC DPI ON -- NÍVEL REGIONAL
				YEAR(CASE
						WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN DP.DATA_DISPARO
						WHEN DP.CODIGO_PESQUISA IN ('102975','103113','104382','106282','108704','108767','109716','111373','111710','114780','115199','115199','115768','118068') THEN '2022-01-18'
						ELSE DP.DATA_RESPOSTA 
					END) = DPI.ANO
				AND
				CASE 
					WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
					WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
					ELSE DE.TIPO_EMPRESA 
				END = DPI.EMPRESA 
				AND 
				CASE 
					WHEN SCD1.NOME_CIDADE = 'SÃO J. DO RIO P' THEN 'SAO JOSE DO RIO PRETO'
					WHEN SCD1.NOME_CIDADE = 'SÃO JOSÉ DO RIO' THEN 'SAO JOSE DO RIO PRETO'
					WHEN SCD1.NOME_CIDADE = 'TAQUARITINGA' THEN 'MATAO'
					WHEN SCD1.NOME_CIDADE = 'VOTORANTIM' THEN 'SOROCABA'
					WHEN  SCD1.NOME_CIDADE IN ('CRAVINHOS', 'JABOTICABAL', 'SERRANA', 'SERTAOZINHO') THEN 'RMRP'
					ELSE SCD1.NOME_CIDADE 
				END	= DPI.REGIONAL
				AND 
				(CASE 
					WHEN DCP.SK_CAMPANHA = 26 THEN 23
					WHEN DCP.SK_CAMPANHA = 27 THEN 24
					ELSE DCP.SK_CAMPANHA
				END) = DPI.SK_D_CAMPANHA
				LEFT JOIN DMDexc.D_PESO_ISC DPIX ON -- NIVEL MACROREGIONAL
					YEAR(CASE
							WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN DP.DATA_DISPARO
							WHEN DP.CODIGO_PESQUISA IN ('102975','103113','104382','106282','108704','108767','109716','111373','111710','114780','115199','115199','115768','118068') THEN '2022-01-18'
							ELSE DP.DATA_RESPOSTA 
						END) = DPIX.ANO
					AND
					CASE 
						WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
						WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
						ELSE DE.TIPO_EMPRESA 
					END = DPIX.EMPRESA 
					AND 
					(CASE 
						WHEN SCD1.NOME_CIDADE IS NULL THEN 'RIBEIRAO PRETO'
						WHEN CASE WHEN SR.NOME_REGIONAL IS NULL THEN SR2.NOME_REGIONAL ELSE SR.NOME_REGIONAL END = 'RIBEIRÃO PRETO' THEN 'RIBEIRAO PRETO'
						WHEN SCD1.NOME_CIDADE = 'UBERABA' THEN 'UBERABA'
						WHEN SR.NOME_REGIONAL = 'MATÃO' THEN 'ARARAQUARA'
						WHEN SR.NOME_REGIONAL = 'CRAVINHOS' THEN 'RIBEIRAO PRETO'
						WHEN SR.NOME_REGIONAL IS NULL AND SCD1.NOME_CIDADE IN ('SERTAOZINHO','JABOTICABAL') THEN 'RIBEIRAO PRETO'
						WHEN SR.NOME_REGIONAL IS NULL AND SCD1.NOME_CIDADE = 'FRANCA' THEN 'FRANCA'
						ELSE SR.NOME_REGIONAL
					END) = DPIX.REGIONAL
					AND 
					(CASE 
						WHEN DCP.SK_CAMPANHA = 26 THEN 23
						WHEN DCP.SK_CAMPANHA = 27 THEN 24
						ELSE DCP.SK_CAMPANHA
					END) = DPIX.SK_D_CAMPANHA
				LEFT JOIN DMDexc.D_PESO_ISC DPIC ON -- NÍVEL CIDADE
					YEAR(CASE
							WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN DP.DATA_DISPARO
							WHEN DP.CODIGO_PESQUISA IN ('102975','103113','104382','106282','108704','108767','109716','111373','111710','114780','115199','115199','115768','118068') THEN '2022-01-18'
							ELSE DP.DATA_RESPOSTA 
						END) = DPIC.ANO
					AND
					CASE 
						WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
						WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
						ELSE DE.TIPO_EMPRESA 
					END = DPIC.EMPRESA 
					AND 
					CASE
						WHEN SCD1.NOME_CIDADE IS NULL THEN 'RIBEIRAO PRETO'
						WHEN SCD1.NOME_CIDADE = 'SÃO J. DO RIO P' THEN 'SAO JOSE DO RIO PRETO'
						WHEN SCD1.NOME_CIDADE = 'SÃO JOSÉ DO RIO' THEN 'SAO JOSE DO RIO PRETO'
						ELSE SCD1.NOME_CIDADE 
					END	= DPIC.REGIONAL
					AND 
					(CASE 
						WHEN DCP.SK_CAMPANHA = 26 THEN 23
						WHEN DCP.SK_CAMPANHA = 27 THEN 24
						ELSE DCP.SK_CAMPANHA
					END) = DPIC.SK_D_CAMPANHA
				LEFT JOIN 
					(SELECT A3.EMPRESA AS V_EMPRESA, A3.EMPREENDIMENTO AS V_EMPREENDIMENTO, A3.DATA_ENVIO V_DATA_ENTREGA_CHAVES, 
						CASE
							WHEN (DATEADD(MONTH,6,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,9,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '6 MESES'
							WHEN (DATEADD(MONTH,12,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,15,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '12 MESES'
							ELSE NULL
						END AS VISAO 
						FROM
						(SELECT A2.EMPRESA AS EMPRESA, A2.EMPREENDIMENTO AS EMPREENDIMENTO, A2.DATA_SYS AS DATA_SYS, MIN(A2.DATA_ENVIO) AS DATA_ENVIO FROM
							(SELECT DISTINCT
								A1.EMPRESA AS EMPRESA, A1.EMPREENDIMENTO AS EMPREENDIMENTO, A1.DATA_ENVIO AS DATA_ENVIO, A1.DATA_SYS AS DATA_SYS,
									COUNT(A1.DATA_ENVIO) AS CONTAGEM
								FROM
									(SELECT DISTINCT
										DP.CODIGO_PESQUISA AS ID_PESQUISA,
										CASE 
											WHEN DP.DATA_CADASTRO IS NULL AND DP.CODIGO_PESQUISA LIKE '%O%' THEN CONVERT(CHAR, DP.DATA_RESPOSTA, 23)
											WHEN DP.DATA_CADASTRO IS NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23)
											ELSE CONVERT(CHAR, DP.DATA_CADASTRO, 23)
										END AS DATA_ENVIO,
										CASE
											WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
											WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
											ELSE DE.TIPO_EMPRESA 
										END AS EMPRESA,
										CASE UPPER(DCP.NOME_CAMPANHA)
											WHEN 'BILD_ENTREGA DE CHAVES' THEN 'ENTREGA DE CHAVES'
											WHEN 'VITTA ENTREGA DE CHAVES' THEN 'ENTREGA DE CHAVES'
											ELSE NULL
										END AS CAMPANHA,
										CASE
											WHEN SE.NOME_EMPREENDIMENTO IS NULL THEN SE2.NOME_FANTASIA_EMPREENDIMENTO
											ELSE SE.NOME_EMPREENDIMENTO
										END AS EMPREENDIMENTO,
										SE.DATA_ENTREGA_REAL_EMPREENDIMENTO AS DATA_SYS
										FROM
											DMDexc.D_PESQUISA DP
												LEFT JOIN DMDexc.D_CAMPOS DC ON DP.SK_D_CAMPOS = DC.SK_CAMPOS
													LEFT JOIN DMDexc.D_EMPREENDIMENTO DE ON DC.SK_D_EMPREENDIMENTO = DE.SK_EMPREENDIMENTO
														LEFT JOIN DMSys.D_REGIONAL SR ON DE.CODIGO_REGIONAL = SR.CODIGO_REGIONAL
												LEFT JOIN DMDexc.D_CAMPANHA DCP ON DP.SK_D_CAMPANHA = DCP.SK_CAMPANHA
													LEFT JOIN DMSys.F_VENDA SV ON DC.CODIGO_VENDA = SV.CODIGO_VENDA
														LEFT JOIN DMSys.D_EMPREENDIMENTO SE ON DE.CODIGO_SYS_EMPREENDIMENTO = SE.CODIGO_EMPREENDIMENTO
															LEFT JOIN DMSys.D_CIDADE SCD ON SE.SK_D_CIDADE_EMPREENDIMENTO = SCD.SK_CIDADE
																LEFT JOIN DMSys.D_TIPO_EMPREENDIMENTO STE ON SV.SK_D_TIPO_EMPREENDIMENTO = STE.SK_TIPO_EMPREENDIMENTO
														LEFT JOIN DMSys.D_EMPREENDIMENTO SE2 ON SV.SK_D_EMPREENDIMENTO = SE2.SK_EMPREENDIMENTO
														LEFT JOIN DMSys.D_REGIONAL SR2 ON SV.SK_D_REGIONAL = SR2.SK_REGIONAL) A1
								WHERE A1.EMPRESA = 'BILD' AND A1.CAMPANHA = 'ENTREGA DE CHAVES' AND A1.DATA_SYS >= '2020-01-01'
								GROUP BY A1.EMPRESA, A1.EMPREENDIMENTO, A1.DATA_ENVIO, A1.DATA_SYS
								HAVING COUNT(A1.DATA_ENVIO) >= 3) A2
							GROUP BY A2.EMPRESA, A2.EMPREENDIMENTO, A2.DATA_SYS) A3
							WHERE (CASE
							WHEN (DATEADD(MONTH,6,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,9,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '6 MESES'
							WHEN (DATEADD(MONTH,12,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,15,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '12 MESES'
							ELSE NULL
						END) IS NOT NULL
					UNION SELECT A3.EMPRESA AS V_EMPRESA, A3.EMPREENDIMENTO AS V_EMPREENDIMENTO, A3.DATA_ENVIO V_DATA_ENTREGA_CHAVES, 
						CASE
							WHEN (DATEADD(MONTH,6,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,9,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '6 MESES'
							WHEN (DATEADD(MONTH,12,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,15,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '12 MESES'
							ELSE NULL
						END AS VISAO 
						FROM
						(SELECT A2.EMPRESA AS EMPRESA, A2.EMPREENDIMENTO AS EMPREENDIMENTO, A2.DATA_SYS AS DATA_SYS, MIN(A2.DATA_ENVIO) AS DATA_ENVIO FROM
							(SELECT DISTINCT
								A1.EMPRESA AS EMPRESA, A1.EMPREENDIMENTO AS EMPREENDIMENTO, A1.DATA_ENVIO AS DATA_ENVIO, A1.DATA_SYS AS DATA_SYS,
									COUNT(A1.DATA_ENVIO) AS CONTAGEM
								FROM
									(SELECT DISTINCT
										DP.CODIGO_PESQUISA AS ID_PESQUISA,
										CASE 
											WHEN DP.DATA_CADASTRO IS NULL AND DP.CODIGO_PESQUISA LIKE '%O%' THEN CONVERT(CHAR, DP.DATA_RESPOSTA, 23)
											WHEN DP.DATA_CADASTRO IS NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23)
											ELSE CONVERT(CHAR, DP.DATA_CADASTRO, 23)
										END AS DATA_ENVIO,
										CASE
											WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
											WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
											ELSE DE.TIPO_EMPRESA 
										END AS EMPRESA,
										CASE UPPER(DCP.NOME_CAMPANHA)
											WHEN 'BILD_ENTREGA DE CHAVES' THEN 'ENTREGA DE CHAVES'
											WHEN 'VITTA ENTREGA DE CHAVES' THEN 'ENTREGA DE CHAVES'
											ELSE NULL
										END AS CAMPANHA,
										CASE
											WHEN SE.NOME_EMPREENDIMENTO IS NULL THEN SE2.NOME_FANTASIA_EMPREENDIMENTO
											ELSE SE.NOME_EMPREENDIMENTO
										END AS EMPREENDIMENTO,
										SE.DATA_ENTREGA_REAL_EMPREENDIMENTO AS DATA_SYS
										FROM
											DMDexc.D_PESQUISA DP
												LEFT JOIN DMDexc.D_CAMPOS DC ON DP.SK_D_CAMPOS = DC.SK_CAMPOS
													LEFT JOIN DMDexc.D_EMPREENDIMENTO DE ON DC.SK_D_EMPREENDIMENTO = DE.SK_EMPREENDIMENTO
														LEFT JOIN DMSys.D_REGIONAL SR ON DE.CODIGO_REGIONAL = SR.CODIGO_REGIONAL
												LEFT JOIN DMDexc.D_CAMPANHA DCP ON DP.SK_D_CAMPANHA = DCP.SK_CAMPANHA
													LEFT JOIN DMSys.F_VENDA SV ON DC.CODIGO_VENDA = SV.CODIGO_VENDA
														LEFT JOIN DMSys.D_EMPREENDIMENTO SE ON DE.CODIGO_SYS_EMPREENDIMENTO = SE.CODIGO_EMPREENDIMENTO
															LEFT JOIN DMSys.D_CIDADE SCD ON SE.SK_D_CIDADE_EMPREENDIMENTO = SCD.SK_CIDADE
															LEFT JOIN DMSys.D_TIPO_EMPREENDIMENTO STE ON SV.SK_D_TIPO_EMPREENDIMENTO = STE.SK_TIPO_EMPREENDIMENTO
														LEFT JOIN DMSys.D_EMPREENDIMENTO SE2 ON SV.SK_D_EMPREENDIMENTO = SE2.SK_EMPREENDIMENTO
														LEFT JOIN DMSys.D_REGIONAL SR2 ON SV.SK_D_REGIONAL = SR2.SK_REGIONAL) A1
								WHERE A1.EMPRESA = 'VITTA' AND A1.CAMPANHA = 'ENTREGA DE CHAVES' AND A1.DATA_SYS >= '2020-01-01'
								GROUP BY A1.EMPRESA, A1.EMPREENDIMENTO, A1.DATA_ENVIO, A1.DATA_SYS
								HAVING COUNT(A1.DATA_ENVIO) >= 40) A2
							GROUP BY A2.EMPRESA, A2.EMPREENDIMENTO, A2.DATA_SYS) A3
							WHERE (CASE
							WHEN (DATEADD(MONTH,6,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,9,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '6 MESES'
							WHEN (DATEADD(MONTH,12,A3.DATA_ENVIO) <= SYSDATETIME()) AND (DATEADD(MONTH,15,A3.DATA_ENVIO) >= SYSDATETIME()) THEN '12 MESES'
							ELSE NULL
						END) IS NOT NULL) VV ON 
							(CASE 
								WHEN DP.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
								WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
								ELSE DE.TIPO_EMPRESA 
							END) = VV.V_EMPRESA
							AND
							(CASE
								WHEN SE.NOME_EMPREENDIMENTO IS NULL THEN SE2.NOME_FANTASIA_EMPREENDIMENTO
								ELSE SE.NOME_EMPREENDIMENTO
							END) = VV.V_EMPREENDIMENTO
	WHERE
		NOT(DP.CODIGO_PESQUISA IN ('19758','104431','104743','104691','104693','104828','104742','104687','104688','104827','104841','104692','104835','104689','104829','104694','O23475','122436','120050','121293'))


	-- EXTRA
		AND (CASE
		WHEN SCD1.NOME_CIDADE IS NULL THEN 'RIBEIRAO PRETO'
		WHEN SCD1.NOME_CIDADE = 'SÃO J. DO RIO P' THEN 'SAO JOSE DO RIO PRETO'
		WHEN SCD1.NOME_CIDADE = 'SÃO JOSÉ DO RIO' THEN 'SAO JOSE DO RIO PRETO'
		ELSE SCD1.NOME_CIDADE 
	END) IS NULL
--		AND SCD1.NOME_CIDADE = 'SAO PAULO'
				AND DP.NOTA_RESPOSTA IS NOT NULL
/*		AND (CASE 
		WHEN CASE WHEN SR.NOME_REGIONAL IS NULL THEN SR2.NOME_REGIONAL ELSE SR.NOME_REGIONAL END = 'RIBEIRÃO PRETO' THEN 'RIBEIRAO PRETO'
		WHEN SCD1.NOME_CIDADE = 'UBERABA' THEN 'UBERABA'
		WHEN SR.NOME_REGIONAL = 'MATÃO' THEN 'ARARAQUARA'
		WHEN SR.NOME_REGIONAL = 'CRAVINHOS' THEN 'RIBEIRAO PRETO'
		ELSE SR.NOME_REGIONAL
	END) IS NULL*/

--		AND DPI.PESO IS NULL
/*	DPIX.PESO AS 'PESO ISC MACROREGIONAL',
	DPI.PESO AS 'PESO ISC REGIONAL',
	DPI.PESO_GERAL AS 'PESO ISC GERAL',
	DPI.META AS 'META ISC REGIONAL',
	DPI.META_GERAL AS 'META ISC EMPRESA',
	DPI.META_NPS AS 'META NPS REGIONAL',
	DPI.META_NPS_GERAL AS 'META NPS EMPRESA',
	DPIC.PESO AS 'PESO ISC CIDADE',
	DPIC.META AS 'META ISC CIDADE',
	DPIC.META_NPS AS 'META NPS CIDADE',*/
--		AND SU.CODIGO_MEGA = 44593
--	AND DP.DATA_CADASTRO >= '2022-01-01'
/*		AND (CASE 
		WHEN CASE WHEN SR.NOME_REGIONAL IS NULL THEN SR2.NOME_REGIONAL ELSE SR.NOME_REGIONAL END = 'RIBEIRÃO PRETO' THEN 'RIBEIRAO PRETO'
		WHEN SCD1.NOME_CIDADE = 'UBERABA' THEN 'UBERABA'
		WHEN SR.NOME_REGIONAL = 'MATÃO' THEN 'ARARAQUARA'
		ELSE SR.NOME_REGIONAL
	END) IS NULL*/
--		AND NOT(DP.CODIGO_PESQUISA LIKE 'O%')
--		AND SU.CODIGO_MEGA IN (33466,33467,33468)
--		AND DP.DATA_CADASTRO >= '2022-01-01'
--		AND DP.CODIGO_PESQUISA = '122186'
--		AND DP.CODIGO_PESQUISA IN ('100476')
--		AND DP.NOTA_RESPOSTA IS NOT NULL
--		AND DCP.NOME_CAMPANHA = 'BILD CRM_ASSISTÊNCIA TÉCNICA'
--		AND DP.DATA_RESPOSTA BETWEEN '2021-01-01 00:00:00' AND '2022-02-18 23:59:59'
--		ORDER BY (CASE WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23) ELSE CONVERT(CHAR, DP.DATA_RESPOSTA, 23) END) DESC
--		AND SC.NOME_CLIENTE LIKE 'ANNEMARIE KASTEN'
--		AND (CASE WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23) ELSE CONVERT(CHAR, DP.DATA_RESPOSTA, 23) END) >= '2022-01-01';

--		AND SCS.NOME_CONSULTOR = 'NICOLE MAGALHAES CARRATU'
--		AND (SCD.NOME_CIDADE = 'CAMPINAS' AND DCP.NOME_CAMPANHA = 'VITTA CRM DISTRATO' AND DP.NOTA_RESPOSTA IS NOT NULL)
--			OR (SCD.NOME_CIDADE = 'SERRANA' AND DCP.NOME_CAMPANHA = 'VITTA 6 MESES DA ENTREGA DE CHAVES' AND DP.NOTA_RESPOSTA IS NOT NULL)
--		AND SE.NOME_EMPREENDIMENTO = 'ATTUALE' AND DCP.NOME_CAMPANHA = 'BILD_ENTREGA DE CHAVES'
--	ORDER BY (CASE WHEN DP.DATA_CADASTRO IS NULL AND DP.CODIGO_PESQUISA LIKE '%O%' THEN CONVERT(CHAR, DP.DATA_RESPOSTA, 23) WHEN DP.DATA_CADASTRO IS NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23) 
--		ELSE CONVERT(CHAR, DP.DATA_CADASTRO, 23) END) ASC
--		AND (CASE WHEN DP.DATA_RESPOSTA IS NULL THEN CONVERT(CHAR, DP.DATA_DISPARO, 23) ELSE CONVERT(CHAR, DP.DATA_RESPOSTA, 23) END) LIKE '2022-01-1%'
--		AND (CASE WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NULL AND DATEADD(DAY,5,DP.DATA_DISPARO) >= SYSDATETIME() THEN 'NÃO' WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NULL AND DATEADD(DAY,5,DP.DATA_DISPARO)
--			< SYSDATETIME() THEN 'SIM' WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NULL AND DP.DATA_DISPARO IS NULL THEN 'NÃO' ELSE 'RESPONDIDA' END) = 'RESPONDIDA'
--		AND NOT(CASE WHEN (DP.TIPO_RESPOSTA IS NULL) AND (DP.NOTA_RESPOSTA IS NOT NULL) THEN 'CLIENTE'	WHEN (DP.TIPO_RESPOSTA = '') AND (DP.NOTA_RESPOSTA IS NOT NULL) THEN 'CLIENTE' WHEN DP.ORIGEM_DISPARO = 'Ligação' THEN 'LIGAÇÃO'
--		WHEN DP.TIPO_RESPOSTA = '' THEN NULL ELSE UPPER(DP.TIPO_RESPOSTA) END) = 'LIGAÇÃO'
--		AND (CASE WHEN DP.DATA_DISPARO IS NULL THEN CONVERT(CHAR, DP.DATA_CADASTRO, 23) WHEN (CASE WHEN DP.DATA_RESPOSTA IS NULL AND DP.NOTA_RESPOSTA IS NOT NULL THEN DP.DATA_DISPARO ELSE DP.DATA_RESPOSTA END
--		< CASE WHEN DP.DATA_DISPARO IS NULL THEN DP.DATA_CADASTRO ELSE DP.DATA_DISPARO END) THEN CONVERT(CHAR, DP.DATA_CADASTRO, 23) ELSE CONVERT(CHAR, DP.DATA_DISPARO, 23) END) LIKE '2021-%'
--		AND NOT(DP.CODIGO_PESQUISA LIKE '%O%')
--		ORDER BY [DATA REFERENCIA TR] DESC
--		AND DCP.NOME_CAMPANHA LIKE '%BILD_ENTREGA DE CHAVES%'
--		AND (CASE WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO ELSE DE.TIPO_EMPRESA END) = 'BILD'
--		AND SC.NOME_CLIENTE LIKE 'ANGELO MICHELETO JUNIOR';
--		AND DP.CODIGO_PESQUISA IN ('O17225','O17011','O15737','O14648','117072','113302','110308','110030');
--		DP.ORIGEM_DISPARO = 'R-WHATSAPP'
--		AND DC.CODIGO_VENDA = '35264'
--		AND SE.NOME_EMPREENDIMENTO = 'vitta lagos do sul';
--		AND NOT(SCS.NOME_CONSULTOR LIKE '%IMOB%')
--		AND DP.NOTA_RESPOSTA <= 6
--		DP.DATA_CADASTRO BETWEEN '2021-11-20 00:00:00' AND '2021-11-20 23:59:59'
--		ORDER BY DP.CODIGO_PESQUISA DESC;

/* 59945
SELECT
	P1.CODIGO_PESQUISA AS 'ID PESQUISA',
	AB.CATEGORIZACAO AS 'CATEGORIZAÇÃO',
	CASE
		WHEN CONVERT(CHAR, VC.DATA_ALTERACAO, 23) IS NULL THEN CONVERT(CHAR, VC.DATA_CADASTRO, 23)
		ELSE CONVERT(CHAR, VC.DATA_ALTERACAO, 23)
	END AS 'DATA CATEGORIZACAO',
	C6.AREA_RESOLVEDORA AS 'ÁREA RESOLVEDORA',
	C6.CATEGORIA AS 'CATEGORIA',
	C6.SUBCATEGORIA_1 AS 'SUBCATEGORIA 1',
	C6.SUBCATEGORIA_2 AS 'SUBCATEGORIA 2',
	C6.SUBCATEGORIA_3 AS 'SUBCATEGORIA 3',
	C6.SUBCATEGORIA_4 AS 'SUBCATEGORIA 4',
	C6.SUBCATEGORIA_5 AS 'SUBCATEGORIA 5',
	C6.SUBCATEGORIA_6 AS 'SUBCATEGORIA 6',
	C6.SUBCATEGORIA_7 AS 'SUBCATEGORIA 7',
	C6.SUBCATEGORIA_8 AS 'SUBCATEGORIA 8' 
	FROM 
		DMDexc.F_VINCULO_CATEGORIA VC
			LEFT JOIN DMDexc.D_CATEGORIA C6 ON VC.SK_D_CATEGORIA = C6.SK_CATEGORIA
			LEFT JOIN DMDexc.D_PESQUISA P1 ON VC.SK_D_PESQUISA = P1.SK_PESQUISA
			LEFT JOIN (SELECT A.SK_CATEGORIA AS SK_CATEGORIA,
				CONCAT(A.AREA_RESOLVEDORA, A.CATEGORIA, A.SUBCATEGORIA_1, A.SUBCATEGORIA_2, A.SUBCATEGORIA_3, A.SUBCATEGORIA_4, A.SUBCATEGORIA_5, A.SUBCATEGORIA_6, A.SUBCATEGORIA_7, A.SUBCATEGORIA_8) AS CATEGORIZACAO
				FROM (SELECT
					SK_CATEGORIA AS SK_CATEGORIA,
					AREA_RESOLVEDORA AS AREA_RESOLVEDORA,
					CASE WHEN CATEGORIA IS NULL THEN ''	ELSE CONCAT(' > ', CATEGORIA) END AS CATEGORIA,
					CASE WHEN SUBCATEGORIA_1 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_1) END AS SUBCATEGORIA_1,
					CASE WHEN SUBCATEGORIA_2 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_2) END AS SUBCATEGORIA_2,
					CASE WHEN SUBCATEGORIA_3 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_3) END AS SUBCATEGORIA_3,
					CASE WHEN SUBCATEGORIA_4 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_4) END AS SUBCATEGORIA_4,
					CASE WHEN SUBCATEGORIA_5 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_5) END AS SUBCATEGORIA_5,
					CASE WHEN SUBCATEGORIA_6 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_6) END AS SUBCATEGORIA_6,
					CASE WHEN SUBCATEGORIA_7 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_7) END AS SUBCATEGORIA_7,
					CASE WHEN SUBCATEGORIA_8 IS NULL THEN '' ELSE CONCAT(' > ', SUBCATEGORIA_8) END AS SUBCATEGORIA_8
					FROM DMDexc.D_CATEGORIA) A
						LEFT JOIN DMDexc.D_CATEGORIA B ON B.SK_CATEGORIA = A.SK_CATEGORIA) AB ON VC.SK_D_CATEGORIA = AB.SK_CATEGORIA
							LEFT JOIN DMDexc.D_CAMPOS DC ON P1.SK_D_CAMPOS = DC.SK_CAMPOS
							LEFT JOIN DMDexc.D_EMPREENDIMENTO DE ON DC.SK_D_EMPREENDIMENTO = DE.SK_EMPREENDIMENTO
							LEFT JOIN DMSys.F_VENDA SV ON DC.CODIGO_VENDA = SV.CODIGO_VENDA
							LEFT JOIN DMSys.D_TIPO_EMPREENDIMENTO STE ON SV.SK_D_TIPO_EMPREENDIMENTO = STE.SK_TIPO_EMPREENDIMENTO
	WHERE
		VC.DATA_DELETE IS NULL
		AND AB.CATEGORIZACAO IS NOT NULL
		AND NOT(P1.CODIGO_PESQUISA IN ('19758','104431','104743','104691','104693','104828','104742','104687','104688','104827','104841','104692','104835','104689','104829','104694','O23475','122436','120050','121293'))
		AND (P1.DATA_DISPARO >= '2021-07-01 00:00:00'
		OR P1.CODIGO_PESQUISA LIKE 'O%')
--	EXTRA
--		AND P1.DATA_RESPOSTA BETWEEN '2021-01-01 00:00:00' AND '2022-02-18 23:59:59'
--		AND C6.AREA_RESOLVEDORA = 'ASSISTENCIA TECNICA'
--		AND (CASE
--		WHEN P1.CODIGO_PESQUISA IN ('102800','105966','108854','108905','109604','O13227','O15555','O16302','O21121','O21815','O22301','O22505','O22792') THEN 'VITTA'
--		WHEN DE.TIPO_EMPRESA IS NULL THEN STE.NOME_TIPO_EMPREENDIMENTO
--		ELSE DE.TIPO_EMPRESA 
--	END) = 'BILD'
		--- EXTRA
--		AND C6.AREA_RESOLVEDORA = 'TI'
--		ORDER BY P1.CODIGO_PESQUISA DESC
*/
/*
SELECT * FROM DMDexc.D_PESQUISA WHERE DATA_PROCESSAMENTO > '2021-12-23' ORDER BY DATA_PROCESSAMENTO DESC
SELECT TOP(10) * FROM DMDexc.D_CAMPOS WHERE CODIGO_CAMPOS = 'C21000'
SELECT * FROM DMDexc.D_CATEGORIA WHERE AREA_RESOLVEDORA LIKE '%ERRAD%'
SELECT * FROM DMDexc.F_VINCULO_CATEGORIA WHERE DATA_DELETE IS NULL AND DATA_CADASTRO BETWEEN '2021-07-01 00:00:00' AND '2021-10-31 23:59:59'
SELECT * FROM DMDexc.D_PESO_ISC WHERE DATA_PROCESSAMENTO > '2021-12-20'
*/